### ISSUE TITLE
Plugin-channel based CUI support

### ISSUE THREAD

**Issue by Pokechu22** [cuberite/WorldEdit#104]
It looks like this supports the old CUI code, based off of chat messages.  That hasn't been used for a pretty long time and now plugin channels are used.

There is some [work in progress plugin channel documentation](http://wiki.vg/Plugin_channels/WorldEditCUI).  I might actually work on updating this to use plugin channels if I find some time.

**Comment by NiLSPACE** [comment]
No, we actually support both: https://github.com/cuberite/WorldEdit/blob/master/Classes/PlayerSelection.lua#L350

**Comment by Pokechu22** [comment]
Whoops, I did a search for "Plugin message" but it didn't find that.
