### ISSUE TITLE
Malformed brush command gives cryptic error message

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/WorldEdit#110]
When executing in-game command `//brush 0 5` (which is malformed - missing the shape param), the server sends a message to the player: `[INFO] Something went wrong while executing command "//brush 0 5"`. However, there's nothing in the server console.

**Comment by NiLSPACE** [comment]
I believe any command with subcommands has this problem. Including those in other plugins.

**Comment by Seadragon91** [comment]
I see that the command `//brush` has the subcommands: c, cyl, cylinder, s and sphere. This are the valid sub commands, passing a other one (//brush a) will result to this message.
Maybe something like that
* Checking if the passed sub commands are valid, if not list the correct ones
* Add a default handler that will be called instead

Currently not sure how that would be possible to do.

**Comment by NiLSPACE** [comment]
I don't think a default handler is required, perhaps it could be optional. If the user tried to use subcommand that doesn't exist and there is no default handler the user should receive a message that it doesn't exist.
