### ISSUE TITLE
Bad syntax implemented for the //replace command

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/WorldEdit#112]
### Expected Behaviour
I'd normally use //replace [block] which would replace the blocks selected using the wand with the specified block which is a whole lot easier and most of the work is done.
### Actual Behaviour
Instead, I am given the effort of finding out the exact names of two blocks, one being the one I currently have selected, and the other being the one I want to change the selected block to.
//replace [Src] [Dst]

### Suggestion
Having the two parameters available is not a bad idea for being more explicit on which block type you want to replace in a specific area, however, the first parameter such be optional.

**Comment by sphinxc0re** [comment]
the command you replacing _every_ block in the specified area is `//set`. `//replace` is used for replacing _only certain_ blocks in the specified area.

**Comment by NiLSPACE** [comment]
As @sphinxc0re already said, the command you're looking for is `//set`. `//replace` accepts 2 parameters with names or ID's of the source and destination blocks. These can be separated with a comma. For example `//replace 1,3 22,20` would replace all stone and dirt with lapis and glass.

**Comment by mohe2015** [comment]
@NiLSPACE non-air I think

**Comment by NiLSPACE** [comment]
Whoops, thanks, I almost uploaded the wrong code ;)
