### ISSUE TITLE
No //fill command

### ISSUE THREAD

**Issue by HelenaKitty** [cuberite/WorldEdit#115]
### Expected behaviour
I expected to be available to fill in areas using //fill
### Actual behaviour
Unknown Command

**Comment by sphinxc0re** [comment]
Are you sure you are not searching for `//set` again? 😁 Although we could add an alias for the `//set` command.

**Comment by mohe2015** [comment]
I think //fill fills areas like a sea but with a specified block instead of water.

**Comment by NiLSPACE** [comment]
I thought `//fill` searches for holes in the ground to fill with a specific block.

**Comment by mohe2015** [comment]
@NiLSPACE that's what I meant.

**Comment by NiLSPACE** [comment]
I doubt it can fill a whole sea though.

**Comment by sphinxc0re** [comment]
http://wiki.sk89q.com/wiki/WorldEdit/Utilities#Filling_pits

**Comment by mohe2015** [comment]
@NiLSPACE I expressed it badly, forget it.

**Comment by HelenaKitty** [comment]
So //set can even change the air blocks?

**Comment by sphinxc0re** [comment]
`//set` will set every block in the selected area regardless of type

**Comment by HelenaKitty** [comment]
I still think //fill should be added to the code, it is traditional to how the original WorldEdit plugin works.

For those that don't know what //fill is for, it is used to fill a specific area of air with any block of choice.

For now, I will adopt the //set method.

**Comment by HelenaKitty** [comment]
I would like to say that //set seems very useful in that you can properly define specific areas to fill.

**Comment by sphinxc0re** [comment]
I believe @NiLSPACE already implemented the fill command on your behalf

**Comment by HelenaKitty** [comment]
Weird, it was missing from my copy of WorldEdit, must have forgotten to update!

**Comment by NiLSPACE** [comment]
I haven't implemented the fill command yet, sorry. I can take a look at it again though. It shouldn't be too hard to implement.

**Comment by NiLSPACE** [comment]
I created the `//fillr` command which was the hardest of the two. I uploaded it in another branch. You can download it here: https://github.com/cuberite/WorldEdit/tree/fill

**Comment by HelenaKitty** [comment]
How would I go about cloning the branch? Sorry, I'm still very new to Github, but I do use the cli to interface with Github.

**Comment by HelenaKitty** [comment]
Great concept of //fill, however there is one bug. In Bukkit and Forge WorldEdit, you fill the pit hole at the level you are standing, in Cuberite WorldEdit, I am required to step up a level to fill the level below me.

I don't personally see this as much of a problem or anything major, though I wouldn't say this is how //fill traditionally works.

Thank you very much for your effort!

**Comment by NiLSPACE** [comment]
Personally I think filling the blocks below the player makes more sense than from the current level. What do you think?

**Comment by HelenaKitty** [comment]
I will give it a try, I think it's a good chance to get stuck into a block if you are spawning blocks where you are stood.
