### ISSUE TITLE
/ rain always crashes in 1.16.2

### ISSUE THREAD

**Issue by Blueeyestar** [cuberite/WorldEdit#145]
Spigot-Version:CraftBukkit version git-Spigot-379750e-9a9c223 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

Worldedit: worldedit-bukkit-7.2.0-SNAPSHOT-dist.jar   #5280

Unfortunately, in 1.16.2 with the latest version, I can no longer make rain without the server crashing.

https://pastebin.com/mUZpSXUS

**Comment by 12xx12** [comment]
I'm sorry - this is not the worldedit for Spigot...

check here; https://github.com/EngineHub/WorldEdit
