### ISSUE TITLE
More //expand options

### ISSUE THREAD

**Issue by madmaxoft** [cuberite/WorldEdit#25]
We should add more "directions" for the `//expand` command:
- `all` / `faces` - expands all directions
- `walls` - expands all four X and Z directions
- `height` - expands the height to the full chunk height (used without the [NumBlocks] arg)

**Comment by NiLSPACE** [comment]
Maybe we should do this as an API. That way other plugins can add options as well.

**Comment by madmaxoft** [comment]
Nah, I don't think it's worth it. If a plugin wants to extend a selection in a way not implemented, they can just make a new command and use the existing WE API to get and set the selection.
