### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by mathias-github** [cuberite/WorldEdit#83]
The plugin doesn't contain a license file at the moment, which means it's automatically copyrighted. It would be a good idea to include an open source license or release the plugin into the public domain, since we accept code contributions.

**Comment by NiLSPACE** [comment]
What about the Apache license like Cuberite.

**Comment by madmaxoft** [comment]
Well, it's mostly your work, @NiLSPACE , so you decide. I do all my stuff under public domain, if there's no other license already in place.

**Comment by mathias-github** [comment]
I personally don't like having to deal with licenses and such, so I'd release it into the public domain/unlicense it. Your decision though.

**Comment by NiLSPACE** [comment]
I added the Apache license
