### ISSUE TITLE
Default direction of block entities like chest should be changed

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/WorldEdit#93]
Copied from [cuberite#2506](https://github.com/cuberite/cuberite/issues/2506)

The default direction of this blocks: ladder, furnace, chest and trapped chest should be 2 instead of 0.
Allowed values are 2, 3, 4, and 5.
I had a problem with setting chests, because I had the meta value 0 and then the block was always invisible.
In Bukkit other values then them above are not allowed. WorldEdit (java one) defaults to 2, if a invalid value is used. Bukkit defaults to 5, don't know why, but I think 2 is better.

How and where should this be implemented in the code?

**Comment by NiLSPACE** [comment]
It would probably have to be implemented [here](https://github.com/cuberite/WorldEdit/blob/master/functions.lua#L40) and [here](https://github.com/cuberite/WorldEdit/blob/master/functions.lua#L26)

Instead of returning 0 we'd do something like this:
```lua
-- Somewhere in a faraway file
local g_DefaultMetas = {
  [Itemtype] = 2,
  [otheritemtype] = 2,
}

-- In the GetBlockTypeMeta function:
return BlockID, g_BlockMetas[BlockID] or 0, true
```
